service: measure-yahoo-finance

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  profile: oldst-main
  environment: ${self:custom.vars}

custom:
  vars: ${file(./serverless.env.yml):${opt:stage, self:provider.stage}}
  serverless-offline:
    http:
      timeout: 30000 # Timeout increased to 30 seconds for serverless-offline

plugins:
  - serverless-python-requirements
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**
    - .pytest_cache/**
    - .serverless/**
    - .git/**

functions:
  status-handler:
    handler: handler.lambda_handler
    events:
      - http:
          path: status
          method: get
          cors: true

  yfinance-handler:
    handler: handler.lambda_handler
    events:
      - http:
          path: yfinance
          method: post
          cors: true

  yfinance-filter-handler:
    handler: handler.lambda_handler
    events:
      - http:
          path: yfinance/filter
          method: post
          cors: true